services:
  german_ner:
    build:
      context: ./build
    ports:
      - 5289:5000
    restart: unless-stopped
    networks:
      - demo_network
    container_name: german_ner_container
    image: german_ner_image


networks:
  demo_network:
    external: true
